apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: RoomsAPI
  description: Room API
spec:
  type: asyncapi
  lifecycle: production
  owner: team-c
  definition: | 
      asyncapi: "2.0.0"
      info:
        description: "Meeting Room"
        version: "1.0.0"
        title: "Swagger Meeting Room"
      host: "localhost:8080"
      schemes:
        - "https"
        - "http"

      tags:
        - name: meetingRoom
          description: Everything about your Meeting Room

      paths:
        /meetingRoom:
          get:
            tags:
              - meetingRoom
            summary: "Find the MeetingRoom"
            description: ""
            operationId: "findAllMeetingRooms"
            produces:
              - "application/json"
            responses:
              "200":
                description: "successful operation"
                schema:
                  type: "array"
                  items:
                    $ref: "#/definitions/MeetingRoom"
          post:
            tags:
              - meetingRoom
            summary: "Add a new meeting room"
            description: ""
            operationId: "addMeetingRoom"
            consumes:
              - "application/json"
            parameters:
              - name: "meetingRoom"
                in: "body"
                schema:
                  $ref: "#/definitions/MeetingRoom"
            produces:
              - "application/json"
            responses:
              "200":
                description: "Ok"
                schema:
                  type: "integer"

        /meetingRoom/{meetingRoomId}:
          get:
            tags:
              - meetingRoom
            summary: "Find MeetingRoom by ID"
            description: ""
            operationId: "findMeetingRoom"
            consumes:
              - "application/json"
            parameters:
              - name: "meetingRoomId"
                in: "path"
                description: "ID della meeting room"
                required: true
                type: "integer"
                format: "int64"
            produces:
              - "application/json"
            responses:
              "200":
                description: "successful operation"
                schema:
                  $ref: "#/definitions/MeetingRoom"
          put:
            tags:
              - meetingRoom
            summary: "Update an existing MeetingRoom"
            description: ""
            operationId: "updateMeetingRoom"
            consumes:
              - "application/json"
            parameters:
              - name: "meetingRoomId"
                in: "path"
                description: "ID della meeting room"
                required: true
                type: "integer"
                format: "int64"
              - name: "Booking"
                in: "body"
                schema:
                  $ref: "#/definitions/MeetingRoom"
            produces:
              - "application/json"
            responses:
              "200":
                description: "Ok"
          delete:
            tags:
              - meetingRoom
            summary: "Deletes a MeetingRoom"
            description: ""
            operationId: "deleteMeetingRoom"
            consumes:
              - "application/json"
            parameters:
              - name: "meetingRoomId"
                in: "path"
                description: "ID della meeting room"
                required: true
                type: "integer"
                format: "int64"
            responses:
              "200":
                description: "Ok"
        /meetingRoom/allBookingForMeetingRoom:
          get:
            tags:
              - meetingRoom
            summary: "Find all Booking for MeetingRoom name"
            description: ""
            operationId: "findBookingForMeetingRoom"
            consumes:
              - "application/json"
            parameters:
              - name: "name"
                in: "query"
                description: "Name della meeting room"
                required: true
                type: "string"
            produces:
              - "application/json"
            responses:
              "200":
                description: "successful operation"
                schema:
                  type: "array"
                  items:
                    $ref: "#/definitions/Booking"
        /meetingRoom/busyOnDates:
          get:
            tags:
              - meetingRoom
            summary: "Find all Meeting Room busy on dates"
            description: ""
            operationId: "busyOnDates"
            consumes:
              - "application/json"
            parameters:
              - in: "query"
                name: "startDate"
                type: "string"
                description: "start date for booking"
              - in: "query"
                name: "endDate"
                type: "string"
                description: "end date for booking"
            produces:
              - "application/json"
            responses:
              "200":
                description: "successful operation"
                schema:
                  type: "array"
                  items:
                    $ref: "#/definitions/MeetingRoom"
        /meetingRoom/meetingRoomDetails:
          get:
            tags:
              - meetingRoom
            summary: "Find meeting room details"
            description: ""
            operationId: "meetingRoomDetails"
            consumes:
              - "application/json"
            parameters:
              - in: "query"
                name: "name"
                type: "string"
                description: "meetingRoomName"
            produces:
              - "application/json"
            responses:
              "200":
                description: "successful operation"
                schema:
                  type: "array"
                  items:
                    $ref: "#/definitions/MeetingRoom"
      definitions:
        MeetingRoom:
          type: "object"
          required:
            - id
            - name
          properties:
            id:
              type: "integer"
              format: "int64"
            name:
              type: "string"
            capacity:
              type: "integer"
              format: "int64"
            dimension:
              type: "integer"
              format: "int64"
        Booking:
          type: "object"
          properties:
            id:
              type: "integer"
              format: "int64"
            userId:
              type: "integer"
              format: "int64"
            meetingRoomId:
              type: "integer"
              format: "int64"
            startDate:
              type: "string"
              format: "time"
            endDate:
              type: "string"
              format: "time"
